# Generated by Django 4.2.4 on 2023-09-09 05:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imageurl',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
