# Generated by Django 4.2.4 on 2023-09-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_post_imageurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(max_length=100)),
                ('C_description', models.TextField()),
                ('C_from', models.PositiveIntegerField()),
                ('C_To', models.PositiveIntegerField()),
                ('C_Place', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('company', models.TextField()),
                ('e_from', models.PositiveIntegerField()),
                ('e_To', models.PositiveIntegerField()),
                ('e_description', models.TextField()),
            ],
        ),
    ]
