# Generated by Django 4.2.4 on 2023-09-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_education_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='e_To',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='e_from',
            field=models.TextField(),
        ),
    ]
