# Generated by Django 4.2.4 on 2023-09-14 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
