# Generated by Django 4.2.5 on 2023-09-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_category_tag_post_categories_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectimgurl',
            field=models.CharField(default='images/iamge_1.jpg', max_length=255),
        ),
    ]
